### ISSUE TITLE
Error 500 after SSO Login

### ISSUE THREAD

**Issue by p-vg** [exodus4d/pathfinder#344]
Login to EVE SSO, select character and then click Authorize and then I get a 500 error. nginx_error.log included below says require.js isn't found, but I can navigate to that path in my www folder and its there. Also of note I don't have an error.log or crest.log in the logs/ directory, even though the nginx logs write successfully in the same location. 

Any and all help would be greatly appreciated, thanks!

```
Error - 500

Oooops, Something went wrong! You have experienced a technical error. We apologize.

Status: 'Internal Server Error'
Message: Call to undefined function Controller\Ccp\json_decode()
```

nginx_error.log
```
2016/10/14 01:59:22 [error] 9127#0: *20 FastCGI sent in stderr: "PHP message: Call to undefined function Lib\json_decode()
PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function Controller\json_encode() in /var/www/pathfinder/html/app/main/controller/controller.php:589
Stack trace:
#0 /var/www/pathfinder/html/app/lib/base.php(1672): Controller\Controller->showError(Object(Base), Array)
#1 /var/www/pathfinder/html/app/lib/base.php(1179): Base->call(Array, Array, Array)
#2 /var/www/pathfinder/html/app/lib/base.php(2026): Base->error(500, 'Call to undefin...', '')
#3 [internal function]: Base->{closure}(Object(Error))
#4 {main}
  thrown in /var/www/pathfinder/html/app/main/controller/controller.php on line 589" while reading response header from upstream, client: ip.ad.dr.ess, server: pathfinder, request: "POST /api/user/getEveServerStatus HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/www.sock:", host: "pathfinder", referrer: "https://pathfinder/"
2016/10/14 01:59:29 [error] 9127#0: *20 FastCGI sent in stderr: "PHP message: Call to undefined function Controller\Ccp\json_decode()" while reading response header from upstream, client: ip.ad.dr.ess, server: pathfinder, request: "GET /sso/callbackAuthorization?code=XXXXXXXXXX&state=09dcdd6dfcf90e58faf4a40d HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/www.sock:", host: "pathfinder", referrer: "https://login.eveonline.com/oauth/authorize?response_type=code&redirect_uri=https%3A%2F%2Fpathfinder%2Fsso%2FcallbackAuthorization&client_id=<STRING>"
2016/10/14 01:59:30 [error] 9127#0: *20 open() "/var/www/pathfinder/html/sso/public/css/pathfinder.css" failed (2: No such file or directory), client: ip.ad.dr.ess, server: pathfinder, request: "GET /sso/public/css/pathfinder.css?v1.1.5 HTTP/1.1", host: "pathfinder", referrer: "https://pathfinder/sso/callbackAuthorization?code=<STRING>"
2016/10/14 01:59:30 [error] 9127#0: *24 open() "/var/www/pathfinder/html/sso/public/js/v1.1.5/lib/require.js" failed (2: No such file or directory), client: ip.ad.dr.ess, server: pathfinder, request: "GET /sso/public/js/v1.1.5/lib/require.js HTTP/1.1", host: "pathfinder", referrer: "https://pathfinder/sso/callbackAuthorization?code=<STRING>"
2016/10/14 01:59:30 [error] 9127#0: *24 open() "/var/www/pathfinder/html/sso/public/js/v1.1.5/lib/require.js" failed (2: No such file or directory), client: ip.ad.dr.ess, server: pathfinder, request: "GET /sso/public/js/v1.1.5/lib/require.js HTTP/1.1", host: "pathfinder", referrer: "https://pathfinder/sso/callbackAuthorization?code=<STRING>"

```

**Comment by exodus4d** [comment]
> Check the disable_functions ini directive to see if json_decode is in that list 

I removed your Secret CREST key from your post.....;) It is not a good idea to post this public.

**Comment by p-vg** [comment]
I'll take a look. Thanks, I thought I had removed everything! Haha 





On Fri, Oct 14, 2016 at 2:14 AM -0400, "Mark Friedrich" <notifications@github.com> wrote:













Check the disable_functions ini directive to see if json_decode is in that list 




I removed your Secret CREST key from your post.....;) It is not a good idea to post this public.

**Comment by p-vg** [comment]
I didn't think so, but I just confirmed -- it's not in the disable_functions directive.

**Comment by p-vg** [comment]
Its amazing how well things work when you actually have the json module for php installed...duh.

 thanks for all of your hard work!
