### ISSUE TITLE
Problem with setup

### ISSUE THREAD

**Issue by Maxcraft90** [exodus4d/pathfinder#418]
So i can see the page which is on a subdomain (map.xyz.com).

As soon as I hit setup, i can only see the following:

![image](https://cloud.githubusercontent.com/assets/20978852/21566035/3ffbdd9a-ce9f-11e6-8ec2-e28a6c50d51c.png)

I already changed the htcaccess cause I am only using http:// and i put everything into the environment.ini, even the whole CREST thingie.

Yet nothing is showing up.

Any ideas where I went wrong?

**Comment by justindh** [comment]
Did you edit the %pathfinderoot%/app/routes.ini and uncomment the setup line?

**Comment by exodus4d** [comment]
If you have still problems with setting up _Pathfinder_ please, send my an E-Mail, Ill invite you to our _Slack_ channel. I´m pretty sure it´s not a bug and just some kind of misconfiguration.

**Comment by toro-** [comment]
seeing this too.

Tried various things. I assume it is do with the rewrite rules, but I am too much of a noob to understand what is going on with them.

I am using Apache

**Comment by ddouglas493** [comment]
@exodus4d any update on this

**Comment by TSarain** [comment]
I am having the same problem.  I started with Apache then switched to Nginx. Same issue.
Seems routes.ini isn't getting processed correctly likely due to a configuration error on my part.

Emailed a request for invite to slack

**Comment by olibob** [comment]
@exodus4d I just ran into this issue.

The routes are uncommented in <pathfinderoot>/app/routes.ini (both when cloning git repo or using a release archive)

Setup is done on fresh ubuntu xenial. I can see the landing page just fine. but 404 not found on setup and admin (sso).

Although the routes are uncommented, there are no setup or admin folders and associated files corresponding to these routes. It's like something is missing to bootstrap.

Please let me know what information I need to provide to get some help. I'm trying to set this up for my corp.

**Comment by fredderf11** [comment]
Did you folks ever figure out what the problem is with the inactive routes? I'm having the same problem and am pretty close to just downing a bottle of scotch...

**Comment by exodus4d** [comment]
For installation please use one of those options:
1. Use a dedicated TLD e.g. `pathfinder-w.space`
2. Use a subdomain e.g. `dev.pathfinder-w.space`

There are some issues with installations in **subDirectories** e.g. `pathfinder-w.space/pathfinder`. SubDir  install is not frequently tested and all my installations use one of the two suggested options.

In both cases `BASE` needs to be **empty** (default setting) in `app/environment.ini` e.g.:
```
[ENVIRONMENT]
SERVER                      =   PRODUCTION

[ENVIRONMENT.PRODUCTION]
BASE                        =
URL                         =   {{@SCHEME}}://www.dev.pathfinder-w.space
```
Better option is to create your own `environment.ini` in a **new** folder `conf/environment.ini` and overwrite all the default stuff. If you have your own `conf/environment.ini`, you need to overwrite **all** default settings from `app/environment.ini`, not just the lines you want to adjust (this might be fixed some day..).

If you have the this set up, and still issues with accessing the page, it´s most likely a _Apache/Nginx_ config issue. Feel free to link your Nginx config here...

**Comment by tonytonyistony** [comment]
I have been trying to solve this problem for days now. The only thing I can isolate as a problem through checking logs is some database errors in the logs folder.

> Wed, 31 Jul 2019 04:06:20 +0000 [68.226.107.33] PDOException: SQLSTATE[HY000] [1698] Access denied for user ''@'localhost' in /var/www/pathfinder/app/lib/db/sql.php:519
Wed, 31 Jul 2019 04:06:20 +0000 [68.226.107.33] Stack trace:
Wed, 31 Jul 2019 04:06:20 +0000 [68.226.107.33] #0 /var/www/pathfinder/app/lib/db/sql.php(519): PDO->__construct('mysql:host=loca...', NULL, NULL, Array)
Wed, 31 Jul 2019 04:06:20 +0000 [68.226.107.33] #1 /var/www/pathfinder/app/main/lib/db/SQL.php(19): DB\SQL->__construct('mysql:host=loca...', NULL, NULL, Array)
Wed, 31 Jul 2019 04:06:20 +0000 [68.226.107.33] #2 /var/www/pathfinder/app/main/lib/db/Pool.php(185): lib\db\SQL->__construct('mysql:host=loca...', NULL, NULL, Array)
Wed, 31 Jul 2019 04:06:20 +0000 [68.226.107.33] #3 /var/www/pathfinder/app/main/lib/db/Pool.php(142): lib\db\Pool->newDB(Array)
Wed, 31 Jul 2019 04:06:20 +0000 [68.226.107.33] #4 /var/www/pathfinder/app/main/controller/controller.php(129): lib\db\Pool->getDB('PF')
Wed, 31 Jul 2019 04:06:20 +0000 [68.226.107.33] #5 /var/www/pathfinder/app/main/controller/controller.php(83): Controller\Controller->initSession(Object(Base))
Wed, 31 Jul 2019 04:06:20 +0000 [68.226.107.33] #6 /var/www/pathfinder/app/main/controller/appcontroller.php(35): Controller\Controller->beforeroute(Object(Base), Array)
Wed, 31 Jul 2019 04:06:20 +0000 [68.226.107.33] #7 /var/www/pathfinder/app/lib/base.php(1870): Controller\AppController->beforeroute(Object(Base), Array, 'Controller\\AppC...')
Wed, 31 Jul 2019 04:06:20 +0000 [68.226.107.33] #8 /var/www/pathfinder/app/lib/base.php(1673): Base->call(Array, Array, Array)
Wed, 31 Jul 2019 04:06:20 +0000 [68.226.107.33] #9 /var/www/pathfinder/index.php(20): Base->run()
Wed, 31 Jul 2019 04:06:20 +0000 [68.226.107.33] #10 {main}

I am at a total loss at how to isolate this issue. The one good thing is its been teaching more about apache2 and nginx. I've also sent an email to you to get access to your slack. I would love to get some feedback on how to set this server up. Until then Im going to just follow @fredderf11 and down a bottle of scotch.

**Comment by tonytonyistony** [comment]
@exodus4d  
I have fixed this issue in my environment. Details below...
OS: Ubuntu 18.04.2 LTS
WebServer: Apache/2.4.29 (Ubuntu)
DB: mysqld  Ver 10.1.40-MariaDB-0ubuntu0.18.04.1 for debian-linux-gnu on x86_64 (Ubuntu 18.04)

I was having the same issues as described above. Anything outside the root directory was not being displayed with a not found error. I did some research on apache blocking stuff outside the root directory and thats where I found my answers. Below are the steps...

**WARNING: This may not be best practice and may compromise your web server.**
1. sudo edit your /etc/apache2/apache2.conf
2. change your AllowOverride in the <Directory /var/www/> to 'FileInfo' and save
3. run the following command 'sudo a2enmod rewrite'
4. sudo edit your /var/www/site-available/<config>.conf
5. make sure your conf file has the following data
`<Directory /var/www/pathfinder-w.space/public_html>`
`    Require all granted`
`    AllowOverride All`
`</Directory>`
6. Restart apache and attempt to browse to /setup or /admin

I would also like to state that after looking at the sample configs from exodus for nginx I noticed that his `/var/www/` file structure was `/var/www/pathfinder-w.space/public_html`. I did change my web setting to mimic this variable as well.

I hope this helps! It took me 3 hard days of cross eyed CLI work!
