### ISSUE TITLE
DB error - SQLSTATE key was too long

### ISSUE THREAD

**Issue by FangyCZ** [exodus4d/pathfinder#740]
I have a brand new installation of pathfinder (just cloned git repo and configured .ini files). When I try to access the page I will receive 500 from the nginx server and in the error log I can see this:

2019/01/05 10:01:43 [error] 692#692: *126 FastCGI sent in stderr: "PHP message: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes [/var/www/pf/app/lib/db/sql.php:226]
PHP message: [app/lib/db/sql.php:226] PDOStatement->execute()
PHP message: [app/lib/db/sql/session.php:191] DB\SQL->exec()
PHP message: [app/main/controller/controller.php:153] DB\SQL\Session->__construct()
PHP message: [app/main/controller/controller.php:76] Controller\Controller->initSession()
PHP message: [app/main/controller/appcontroller.php:30] Controller\Controller->beforeroute()
PHP message: [index.php:23] Base->run()
PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes in /var/www/pf/app/lib/db/sql.php:226
Stack trace:
#0 /var/www/pf/app/lib/db/sql.php(226): PDOStatement->execute()
#1 /var/www/pf/app/lib/db/sql/session.php(191): DB\SQL->exec(Array)
#2 /var/www/pf/app/main/controller/controller.php(153): DB\SQL\Session->__construct(Object(DB\SQL), 'sessions', true, Object(Closure))
#3 /var/www/pf/app/main/controller/controller.php(76): Controller\Controller->initSession(Object(Base))
#4 /var/www/pf/app/lib/base.php(1831): Controller\Controller->beforeroute(Object(Base), Array)
#5 /var/www/pf/app/lib/base.php(1270): Base->call(Array, Array, Array)
#6 /var/www/pf/app/lib/base.php(2213): Base->error(500, 'SQLSTATE[42000]...', '[app/lib/db/sql...')
#7 [internal function]: Base->{closure}(Object(PDOException))
#8 {main}
  thrown in /var/www/pf/app/lib/db/sql.php on line 226" while reading response header from upstream, client: 10.10.10.10, server: pf.xxx.cz, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "pf.xxx.cz"
 
Can someone help me to solve this?
Thanks, guys.

Debian, Nginx 1.10.3, PHP 7.0.33 FastCGI, MariaDB 10.1, nginx is running only one virtualhost with pathfinder

**Comment by bomkallo** [comment]
You've got wrong DB version or badly created databases.

**Comment by FangyCZ** [comment]
> You've got wrong DB version or badly created databases.

I can try a different version, but there is a limit 767 bytes for InnoDB and 1000 for MyISAM I think.

**Comment by lord-carlos** [comment]
I got the same error, but I can't find any error in my .ini files.
What did you do?
I'm running `mariadb  Ver 15.1 Distrib 10.1.37-MariaDB`
The same I got working in a WM. I can't remember what I did differently this time.

**Comment by FangyCZ** [comment]
> I got the same error, but I can't find any error in my .ini files.
> What did you do?
> I'm running `mariadb Ver 15.1 Distrib 10.1.37-MariaDB`
> The same I got working in a WM. I can't remember what I did differently this time.
> 
> Edit: Not sure why, but it seems to be a [bug in mariadb that](https://jira.mariadb.org/browse/MDEV-14904?focusedCommentId=115604&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-115604) already should have been fixed. Following the steps in the bug report and recreating the database fixed it for me.

FYI: I used custom .ini files in /conf/ directory and they were incomplete (some variables were missing).
